title: Upagraha
description: Space & Technology Club
baseurl: "/Upagraha"
url: "https://sally071-glitch.github.io"

# Build settings
markdown: kramdown
theme: null

# Navigation
nav:
  - title: About
    url: /
  - title: Achievements
    url: /achievements
  - title: Projects
    url: /projects
  - title: Sponsors
    url: /sponsors

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
