title: Upagraha
description: Space & Technology Club
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: null

# Navigation
nav:
  - title: About
    url: /
  - title: Achievements
    url: /achievements
  - title: Projects
    url: /projects
  - title: Sponsors
    url: /sponsors
